crypto_data_warehouse:
  outputs:
    dev:
      dataset: dw_crypto
      fixed_retries: 1
      keyfile: /secrets/dbt-admin_credential.json
      location: US
      method: service-account
      priority: interactive
      project: nice-road-340704
      threads: 1
      timeout_seconds: 300
      type: bigquery
  target: dev